### ISSUE TITLE
QMK settings not working

### ISSUE THREAD

**Issue by linkpy** [vial-kb/vial-qmk#522] opened 2023-08-12 21:05 UTC
using keymap : https://github.com/linkpy/vial-qmk/tree/vial/keyboards/splitkb/aurora/sofle_v2/keymaps/vial

with qmk settings enabled, changing tapping term doesnt do anything (even setting it to a very high value like 1000ms doesnt seem to have any impact on the actual tap-hold behaviours).

i only tested this with LT_n keys.

to reproduice : 
- enable qmk settings 
- flash
- try to change the tapping term with the vial app
- notice nothing changes regarding key rolls and LT_n keys

**Comment by stefanheyder** [comment] 2023-08-31 08:29
I am encountering the same issue which make using home row mods with QMK keys unusable unfortunately. Even using absurdly high tapping terms (800) still results in lots of misfires.

**Comment by xyzz** [comment] 2023-09-03 03:53
I couldn't reproduce the issue with LT_n, please provide better/more detailed reproduction steps.

**Comment by XavRan** [comment] 2023-12-05 23:47
Facing the same problem on default cantor keymap [https://github.com/linkpy/vial-qmk/tree/vial/keyboards/cantor](https://github.com/linkpy/vial-qmk/tree/vial/keyboards/cantor) I am able to change the tapping term from QMK settings, but rolling 2 keys within the tapping term simply activates the modifier. Just like permissive hold. Even though it is disabled.

**Comment by xyzz** [comment] 2024-01-21 19:02
I'm closing this issue because no reproduction steps were provided and we cannot act on this issue.

> Facing the same problem on default cantor keymap

I don't see any modifier keys on the linked keymap so I'm not sure how you are running into the same issue.

**Closed as completed by xyzz** 2024-01-21 19:02 UTC
